### PR TITLE
Made starter items/weapons easier to configure

### PR DESCRIPTION
**Pull request by SimpleSandman**
- Added error handling for NULL values for OnNewCharacter().
- Added working example of adding a weapon without ammo tied to it.
- Replaced // comments with _ elements for inline commenting.

Here's the build for testing and deployment:
[build.zip](https://github.com/VORPCORE/VORP-Inventory/files/8444519/build.zip)

### CODE REVIEW

**Comment by Local9** [comment]
if "_name" is a comment, just change it to "_comment", then when using JSON to Class (NewtonSoft JSON Convert), that field can just be ignored, but I would recommend converting it to a class as all the JSON Object methods we see, need to be refactored out.

**Comment by outsider31000** [comment]
yeah it does create confusion but for me, it tells me that the same comment already exists so I guess using _Coment1 _Coment2 would solve it? as for the code can we merge this boss?

**Comment by SimpleSandman** [comment]
> if "_name" is a comment, just change it to "_comment", then when using JSON to Class (NewtonSoft JSON Convert), that field can just be ignored, but I would recommend converting the JSON to a class as all the JSON Object methods we see, need to be refactored out.
> This means we can then add methods to the class to get information in a nicer way, and in a way the application expects.

For each element in an array, that's fine, but this means we cannot have more than one root comment.

I was thinking of making this conversion myself on some of the smaller repos as this would enforce strong-typing, but without any standardization in the configs, this would be difficult for the C# side to maintain since the Lua devs can just walk in and add a random property to one element without the C# dev's consent. This would be especially painful for the 71 weapons we have in this repo's config.

> I'd also ask, more commits, I'd rather see each change as a commit as its easier to track changes to a file, if a commit is a bunch of files, it can be hard to find or track an issue.

I'll do my best to break up my changes into more commits in the future

**Comment by Local9** [comment]
> Actually now that I think about it, we can just not reference any "_" elements from the C# side. But that doesn't solve the possibility of rouge data elements inside the config unless we make sure in our reviews to force the contributor to add the property into all of the elements in an array.
> 
> This would also mean each `AmmoHash` and `CompsHash` have to follow the same structure (empty or otherwise). Which at the moment, they don't.

True, honestly I'd rather not have comments in the config, but instead improve the documentation for the config, we have a Wiki tab and even a readme.md, might as well use it. This way the config can stay cleaner and not contain data that isn't used, which is a benefit for bandwidth.

**Comment by outsider31000** [comment]
That sounds like a reasonable solution.

**Comment by SimpleSandman** [comment]
I agree on that solution. Something else I've noticed with the current READMEs from a lot of the repos is that it doesn't explain the folder structure very well to people who can't infer. I was able to thanks to experience, but there are others that aren't so fortunate.

**Comment by outsider31000** [comment]
that is on my todo list xD

**Pull request merged**
