### PR TITLE
chore(inventory/refactor): Refactor Inventory Client and Configuration Handling

### PR DESCRIPTION
**Pull request by Local9**
- Refactored the configuration handling so the method is shared between the client and the server
- Updated fxmanifext to cerulean, this means all NUI posts are now https
- config.lua is now a shared_script
- config.json refactored, some items now work as expected for a valid JSON format
- Config initial refactoring in the server and client to use the Config.cs and try to remove JObject where possible
- Restarting the inventory will now request the items table and the characters inventory
Various other changes, best to go over the commits to find anything directly.

Example of how another resource can register useable items if the vorp_inventory is restarted.
```lua
VorpInv = exports.vorp_inventory:vorp_inventoryApi()

AddEventHandler('onResourceStart', function(resourceName)
	  if (resourceName ~= "vorp_inventory") then
		  return
	  end
	  VorpInv.RegisterUsableItem("consumable_lock_breaker", function(data)
		  VorpInv.CloseInv(data.source)
		  TriggerClientEvent("bulgar_doorlocks_vorp:opendoor", data.source, true)
	  end)
end)
```

Edit: updated lua example

### CODE REVIEW

**Comment by Local9** [comment]
Current minimal build from this PR; [vorp_inventory.zip](https://github.com/VORPCORE/VORP-Inventory/files/8459153/vorp_inventory.zip)

**Comment by Local9** [comment]
Require Testing;
- Containers
- Steal
- House
- Clan
- Wagon
- Give Item
- Drop Item

And any other areas I may of forgotten.

Pending changes;
- NUI Objects to become "real" C# Objects, this is to remove ExpandoObjects
- Remove any areas that have dynamic and turn these into real classes
- Weapon, Item, WeaponClass, and ItemClass all require reviewing and refactoring. Duplication needs to be removed
- Its known that classes cannot be sent over events (which is why dynamic and expando is used), so all events will require updating when using classes to use NewtonSoft.

**Comment by t3chman** [comment]
From a fresh install, it seems to load inventory items for the character and remove items/weapons appropriately, but adding items/weapons is not working. Dropping items removes the item from the inventory, but it places the dropped item box and label at a distance (not sure if this is new) - coordinate issue of some kind.

**Comment by Local9** [comment]
https://www.youtube.com/watch?v=hrXr4yGSjZw

Items should now update correctly, there was an issue with the config mapping in the class.

**Comment by SimpleSandman** [comment]
So after pulling down this branch and building it on my machine, I was able to get into my inventory on an existing character successfully.

The problem I'm having at the moment is consuming an item. This problem is also in the master branch. So it might be on my end in terms of something not being updated.
```
[script:vorp_inventor] [ERROR] Item 'consumable_pear' doesn't exist as a usable item
```

I'm using `/giveitem 1 consumable_pear 1` and I'm not able to consume it. I was able to "consume" ammo for my varmint rifle just fine.

What did you do to turn on TRACE?

**Comment by outsider31000** [comment]
Add the item to vorp metabolism.  Its there that you register consumable items.

**Comment by SimpleSandman** [comment]
> Add the item to vorp metabolism. Its there that you register consumable items.

Oh okay! I thought I was missing something. I'll try that when I have some time today

**Comment by Local9** [comment]
> What did you do to turn on TRACE?

https://github.com/VORPCORE/VORP-Inventory/blob/374b9747b96cbb0e1a7a0fabdbc388e02ff4d2c4/VORP-Inventory/VORP.Inventory.Shared/Diagnostics/Logger.cs#L22

fxmanifest.lua, the `log_level` I might of left as `all` should be set to `none` in releases.

**Comment by Local9** [comment]
Forgot to mention, metabolism was also updated to go along side this; https://github.com/VORPCORE/VORP-Metabolism

**Comment by SimpleSandman** [comment]
This might be low priority, but out of observation, the `TRACE` doesn't show my varmint rifle, but the `loadout` table does. Though now that I'm looking at the inventory size in my satchel, I for some reason have 0/200.

I just reran the command `/givewep 1 WEAPON_RIFLE_VARMINT 1` just in case and it still shows 0.

charidentifier, name, ammo, components, dirtlevel, mudlevel, conditionlevel, rustlevel, used, used2, dropped, comps, label
image

image

---------

I gave myself 6 varmint rifles, and the terminal still shows the same empty inventory for my character.

image

**Comment by SimpleSandman** [comment]
Inside the game's F8 terminal, I actually get the `TRACE` and this is my output for the inventory which looks correct
```
[   1874438] [b1436_GTAProce]             MainThrd/ [TRACE] INVENTORY: {"action":"setItems","itemList":[{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2327,"used":true},
{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2328,"used":false},
{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2329,"used":false},
{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2330,"used":false},
{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2331,"used":false},
{"count":0,"limit":-1,"label":"WEAPON_RIFLE_VARMINT","name":"WEAPON_RIFLE_VARMINT","hash":-570967010,"type":"item_weapon","usable":true,"canRemove":true,"id":2332,"used":false}]}
```

**Comment by Local9** [comment]
image

**Comment by Local9** [comment]
https://www.youtube.com/watch?v=rmH5UrZjlH4

**Pull request merged**
