### PR TITLE
Fixes to Config.json

### PR DESCRIPTION
**Pull request by Hailey-Ross**
Fixes minor typos in Config.json that cause errors when trying to give player Advanced Camera and Binoculars

### CODE REVIEW

**Comment by outsider31000** [comment]
@Hailey-Ross  they seem to be the same? i don't see where the typo is

**Comment by outsider31000** [comment]
image
they seem the same

**Comment by Hailey-Ross** [comment]
lower case "k" instead of uppercase "K" in Kit for both names

**Comment by Hailey-Ross** [comment]
very hard to see, search for case specifics to find it in VS Code

**Comment by outsider31000** [comment]
ahah nice catch yeah difficult to find indeed thank you.

**Pull request merged**
