### PR TITLE
(Refactor) Replaced "Java" syntax for Model classes

### PR DESCRIPTION
**Pull request by SimpleSandman**
This improves coding standards by fixing the style of code from the classic Java "getter and setter" syntax to the .NET standard.

Both client and server have been affected by this PR, but the performance and functionality have not. This is merely a much-needed refactor.

### CODE REVIEW

**Comment by Local9** [comment]
My only concern is the case changing of properties as these classes maybe used in some ugly dynamic dictionary thats sent via an export. Using DataContract and DataMember should allow keeping the original naming for when the object is converted to JSON.

The property Count, as this should never go below zero, wouldn't a uint be better for data integrety, we'd need handling possible legacy data where it is below zero would be required.

**Comment by SimpleSandman** [comment]
> My only concern is the case changing of properties as these classes maybe used in some ugly dynamic dictionary thats sent via an export. Using DataContract and DataMember should allow keeping the original naming for when the object is converted to JSON.

We can slap `DataContract` and `DataMember` on all of those properties if that would help prevent garbage dynamic input. I usually use some kind of attribute for JSONs for assigning camel-case values in the original input with pascal-case properties in C#. Would you like for me to add that stuff and test it?

> The property Count, as this should never go below zero, wouldn't a uint be better for data integrety, we'd need handling possible legacy data where it is below zero would be required.

I didn't think about using a `uint` for this particular case as I was thinking of keeping the database datatype and the C# datatypes the same.

**Comment by Local9** [comment]
Thats find for the uint, it would be problematic if someone did put a -1 in there though, as the logic won't pass when checking to see if the count is zero, maybe a less than or equal logic check?

Slapping the data contract and members would be good for any JSON conversion, and then you can add an override for ToString that returns `this.ToJson()`, the extension should already be there.

**Comment by SimpleSandman** [comment]
I'll make both of those happen later today as I still have a little bit of work left for the day (started the work day early today).

**Comment by SimpleSandman** [comment]
Inside `Items.cs`, I've noticed an issue with the misspelling of one of the dictionary strings, "usabel" when it needs to be called, "usable". I can confirm this has been in the repo since 6/20/2020 before Blue worked on this class file a year later.

For the sake of our sanities, I'm going to fix this typo, but we will need to test for this fix.

**Comment by SimpleSandman** [comment]
Alright @Local9 would you mind reviewing what I have committed now?

**Comment by Local9** [comment]
Its just an extension, that uses NewtonSoft. Its just a catch on the ToString that if used, it will output to json and save having to write `myWeaponObject.ToJson()` all the time, so `$"{myWeaponObject}"` will just print the JSON string. Its non-important right now but its something that can be used as and when, as long as everything is working, and the JSON is the same as it was before, all should be fine with other resources that use that data.

```cs
// VORP.Inventory.Shared
public static string ToJson(this object obj)
{
    return JsonConvert.SerializeObject(obj);
}
```

The fixing of the spelling mistake, all is good, other resources will just have to fix theirs if they use it.

**Review by Local9 — APPROVED** [review]
I'm happy with merging this as it stands now, no required changes.

**Pull request merged**
